version: "3"

services:
  alice:
    build: ./ssb
    volumes:
      - ./data/alice:/root/.ssb
    container_name: alice-1
    networks:
      net_alice:
        ipv4_address: 10.10.1.10
    ports:
      - "8008:8008"
      - "8007:8007"  # Alice's SSB peer port
  
  bob:
    build: ./ssb
    volumes:
      - ./data/bob:/root/.ssb
    container_name: bob-1
    networks:
      net_bob:
        ipv4_address: 10.10.2.10
    ports:
      - "8009:8008"
      - "8017:8007"  # Bob's SSB peer port (different external port)
  
  carol:
    build: ./ssb
    volumes:
      - ./data/carol:/root/.ssb
    container_name: carol-1
    networks:
      net_carol:
        ipv4_address: 10.10.3.10
    ports:
      - "8010:8008"
      - "8027:8007"  # Carol's SSB peer port (different external port)

networks:
  net_alice:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
  net_bob:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
  net_carol:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24