#Specifying the Docker Compose file format
version: "3"

#Defines three services
services:
  #container name
  alice:
    #the path to the Dockerfile (from here)
    build: ./ssb
    #links the container storage to my machine's storage
    #the folder .data on my Windows machine is linked to the folder /data in the container
    #this makes sure that alice's follow data, her feed, and her secrets are persisted when 
    # I shut the containers down 
    volumes:
      - ./data/alice:/root/.ssb/flume
    container_name: alice-1
    networks:
      net_alice:
        ipv4_address: 10.10.1.10
    ports:
      - "8008:8008"
  bob:
    build: ./ssb
    volumes:
      - ./data/bob:/root/.ssb/flume
    container_name: bob-1
    networks:
      net_bob:
        ipv4_address: 10.10.2.10
    ports:
      - "8009:8008"
  carol:
    build: ./ssb
    volumes:
      - ./data/carol:/root/.ssb/flume
    container_name: carol-1
    networks:
      net_carol:
        ipv4_address: 10.10.3.10
    ports:
      - "8010:8008"

networks:
  net_alice:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
  net_bob:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
  net_carol:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
    